model:
  type: YoloX-L
  num_classes: 80

training:
  data:
    rootPath: ../Data/COCO
    imgPath: train2017
    annoPath: annotations/instances_train2017.json
    imgSize:
      - 416
      - 416

  GPUIdx: 0
  batchSize: 1
